version: "3.7"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepass
      POSTGRES_DB: sampledb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: