CREATE TABLE IF NOT EXISTS users
(
    id   VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS todos
(
    id      VARCHAR(255) PRIMARY KEY,
    text    VARCHAR(255) NOT NULL,
    done    BOOLEAN      NOT NULL,
    user_id VARCHAR(255) NOT NULL REFERENCES USERS (id)
)
